"""Calibrated hourly profiles per configuration.

Weather, photovoltaic availability, electrical load, and heat demand are
generated by deterministic seasonal models whose annual totals match documented
country values. Every series is reproducible from SEED. The horizon is four
representative weeks (one per season), each carrying an annualization weight.
"""
from __future__ import annotations
import numpy as np
from dataclasses import dataclass
from typing import Dict
import config as C

TAMB_MEAN = {
    "DK": {"winter": 2, "spring": 8,  "summer": 17, "autumn": 9},
    "IE": {"winter": 6, "spring": 9,  "summer": 15, "autumn": 10},
    "SE": {"winter": -2, "spring": 6, "summer": 17, "autumn": 7},
    "DE": {"winter": 2, "spring": 9,  "summer": 19, "autumn": 10},
    "AT": {"winter": 0, "spring": 9,  "summer": 19, "autumn": 10},
    "TR": {"winter": 8, "spring": 15, "summer": 27, "autumn": 17},
    "RO": {"winter": 0, "spring": 11, "summer": 23, "autumn": 12},
}
SOLAR_SEASON = {
    "north": {"winter": 0.22, "spring": 0.70, "summer": 1.00, "autumn": 0.42},
    "south": {"winter": 0.45, "spring": 0.80, "summer": 1.00, "autumn": 0.58},
}
DAYLIGHT_H = {
    "north": {"winter": 8,  "spring": 13, "summer": 17, "autumn": 11},
    "south": {"winter": 10, "spring": 13, "summer": 15, "autumn": 11},
}
SOUTH = {"TR", "RO"}
TAMB_DAILY_AMP = 4.0
HEAT_BASE_T = 15.0
DESIGN_DT = 30.0


def _hour_of_day(n):
    return np.arange(n) % 24


def _solar_shape(region, season, n):
    hod = _hour_of_day(n)
    half = DAYLIGHT_H[region][season] / 2.0
    x = (hod - 12.0) / half
    bell = np.where(np.abs(x) < 1.0, np.cos(0.5 * np.pi * x) ** 2, 0.0)
    return bell * SOLAR_SEASON[region][season]


def _load_shape(arch: "C.Archetype", n):
    hod = _hour_of_day(n)
    morning = np.exp(-0.5 * ((hod - 8) / 2.2) ** 2) * arch.occ_morning
    evening = np.exp(-0.5 * ((hod - 19) / 2.5) ** 2) * arch.occ_evening
    midday = np.exp(-0.5 * ((hod - 13) / 3.5) ** 2) * (0.6 if arch.kind in ("commercial", "office", "public") else 0.25)
    shape = 0.55 + morning + evening + midday
    return shape / shape.mean()


@dataclass
class PilotData:
    pid: str
    T: int
    dt: float
    season: np.ndarray
    days_weight: np.ndarray                             # annualization weight per step [days/step]
    Tamb: np.ndarray
    price_imp: np.ndarray
    price_exp: np.ndarray
    tariff: np.ndarray
    ef: np.ndarray
    ef_dh: float
    agents: Dict[str, dict]
    hosting_limit: float


def build_pilot_data(pid: str, seed: int = C.SEED) -> PilotData:
    pilot = C.PILOTS[pid]
    zone = C.ZONES[pilot.zone]
    region = "south" if pilot.country in SOUTH else "north"
    rng = np.random.default_rng(seed + 17 * list(C.PILOTS).index(pid))

    hps = C.HOURS_PER_SEASON
    T = hps * len(C.SEASONS)
    season = np.concatenate([[s] * hps for s in C.SEASONS])
    days_weight = np.concatenate([[C.SEASON_WEIGHT[s] / (hps / 24.0)] * hps for s in C.SEASONS])

    Tamb = np.zeros(T)
    solar = np.zeros(T)
    for i, s in enumerate(C.SEASONS):
        sl = slice(i * hps, (i + 1) * hps)
        hod = _hour_of_day(hps)
        daily = -TAMB_DAILY_AMP * np.cos(2 * np.pi * (hod - 15) / 24.0)
        Tamb[sl] = TAMB_MEAN[pilot.country][s] + daily + rng.normal(0, 1.2, hps)
        cloud = np.clip(rng.beta(5, 2, hps), 0.2, 1.0)
        solar[sl] = _solar_shape(region, s, hps) * cloud

    hod_full = _hour_of_day(T)
    diurnal = np.sin(2 * np.pi * (hod_full - 7) / 24.0)
    price_imp = np.clip(zone.price_mean + zone.price_amp * diurnal + rng.normal(0, 0.01, T), 0.01, None)
    price_exp = zone.export_ratio * price_imp
    tariff = np.full(T, zone.tariff_use)
    ef = np.clip(zone.ef_mean + zone.ef_amp * diurnal + rng.normal(0, 0.01, T), 0.005, None)

    pv_norm = np.clip(solar.copy(), 0.0, None)
    ann_norm = float(np.sum(pv_norm * days_weight * C.DT))
    yield_country = C.PV_YIELD[pilot.country]
    cop_avg = float(np.clip(C.COP0 + C.KAPPA_COP * (np.mean(Tamb) - 7.0), C.COP_MIN, C.COP_MAX))

    agents = {}
    demand_eq = {}                                      # annual electricity-equivalent demand per agent [kWh]
    for a in pilot.agents:
        arch = C.ARCH[a.archetype]
        shape = np.tile(_load_shape(arch, 24), T // 24 + 1)[:T]
        season_load = np.where(np.isin(season, ["winter", "autumn"]), 1.10, 0.92)
        load = np.clip(arch.base_load_kw * shape * season_load * (1 + rng.normal(0, 0.05, T)), 0.0, None)
        shift_frac = 0.25 if a.flex else 0.0
        Dshbase = shift_frac * load
        Dfix = (1 - shift_frac) * load

        design_load = arch.heat_kw_per_m2 * arch.floor_m2
        hdh = np.clip((HEAT_BASE_T - Tamb) / DESIGN_DT, 0.0, 1.2)
        occ = 0.6 + 0.4 * (shape / shape.max())
        Dheat = design_load * hdh * occ
        if pilot.country == "TR":
            Dheat *= 0.7
        Qpvt = a.pvt_kwp * solar if a.pvt_kwp > 0 else np.zeros(T)

        w = days_weight * C.DT
        e_elec = float(np.sum(load * w))
        cop_use = cop_avg if a.hp else 1.0
        e_heat = max(0.0, float(np.sum((Dheat - Qpvt) * w))) / cop_use
        demand_eq[a.aid] = e_elec + e_heat

        agents[a.aid] = dict(
            Dfix=Dfix, Dshbase=Dshbase, Dheat=Dheat, Qpvt=Qpvt,
            batt_kwh=a.batt_kwh, batt_kw=a.batt_kw, hp=a.hp,
            tes_kwh=a.tes_kwh, tes_kw=a.tes_kw, dh=a.dh, flex=a.flex,
            floor_m2=arch.floor_m2, pv_kwp=0.0,
        )

    # Size the renewable portfolio to the positive-energy target, allocated by roof area.
    target_res = pilot.ped_ratio * sum(demand_eq.values())
    roof = {a.aid: C.ARCH[a.archetype].floor_m2 for a in pilot.agents}
    roof_tot = sum(roof.values())
    for a in pilot.agents:
        e_pv = target_res * roof[a.aid] / roof_tot
        kwp = max(e_pv / max(yield_country, 1e-6), a.pv_kwp)
        scale = (kwp * yield_country) / max(ann_norm, 1e-6)
        agents[a.aid]["PVavail"] = pv_norm * scale
        agents[a.aid]["pv_kwp"] = kwp

    return PilotData(
        pid=pid, T=T, dt=C.DT, season=season, days_weight=days_weight,
        Tamb=Tamb, price_imp=price_imp, price_exp=price_exp, tariff=tariff,
        ef=ef, ef_dh=zone.ef_dh, agents=agents, hosting_limit=pilot.hosting_limit_kw,
    )


def annual_summary(d: PilotData) -> dict:
    w = d.days_weight * d.dt
    pv = sum(np.sum(a["PVavail"] * w) for a in d.agents.values())
    dfix = sum(np.sum(a["Dfix"] * w) for a in d.agents.values())
    dsh = sum(np.sum(a["Dshbase"] * w) for a in d.agents.values())
    heat = sum(np.sum(a["Dheat"] * w) for a in d.agents.values())
    return dict(
        pv_MWh=pv / 1000, elec_dem_MWh=(dfix + dsh) / 1000, heat_dem_MWh=heat / 1000,
        price_mean=float(np.mean(d.price_imp)), ef_mean=float(np.mean(d.ef)),
        Tamb_range=(float(d.Tamb.min()), float(d.Tamb.max())),
    )


if __name__ == "__main__":
    for pid in C.PILOTS:
        s = annual_summary(build_pilot_data(pid))
        print(f"{pid:10s} PV {s['pv_MWh']:6.0f} MWh | elec {s['elec_dem_MWh']:6.0f} MWh | "
              f"heat {s['heat_dem_MWh']:6.0f} MWh | price {s['price_mean']:.3f} | EF {s['ef_mean']:.2f}")
